name = "cartcloser"
client_id = ""
application_url = "SHOPIFY_APP_URL_PLACEHOLDER"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration
scopes = "write_discounts,read_orders,read_products"

[auth]
redirect_urls = [
  "SHOPIFY_APP_URL_PLACEHOLDER/auth/callback",
  "SHOPIFY_APP_URL_PLACEHOLDER/auth/shopify/callback",
  "SHOPIFY_APP_URL_PLACEHOLDER/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled", "customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"

[pos]
embedded = false
